baseURL = "https://tomas-rodriguez-gamboa.github.io/pagina-web/"
languageCode = "es-es"
title = "Tomás Rodríguez Gamboa"
theme = "hugo-goa"

[params]
    author = "Tomás Rodríguez Gamboa"
    intro = "Economista "
    description = "Research Assistant & MSc Economics student at Universidad Alberto Hurtado (Chile)."    #
    authorimage = "perfil.jpg"

[params.social]
    github = "tomas-rodriguez-gamboa"
    linkedin = "tomas-rodriguez-gamboa"
    email = "TORODRIG@ALUMNOS.UAHURTADO.CL"
    twitter = "TomasRIG"

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 10

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 20