
baseURL = "https://tomas-rodriguez-gamboa.github.io/pagina-web/"
languageCode = "es-es"
title = "Tomás Rodríguez Gamboa"
theme = "hugo-goa"

[params]
    author = "Tomás Rodríguez Gamboa"
    intro = "Economist"
   description ="Research Assistant & MSc Economics Candidate at Universidad Alberto Hurtado (Chile)."    #
    authorimage = "perfil.jpg"

[params.social]
    github = "tomas-rodriguez-gamboa"
    linkedin = "tomas-rodriguez-gamboa"
    email = "TORODRIG@ALUMNOS.UAHURTADO.CL"
    twitter = "TomasRIG"

[[menu.main]]
    name = "Research"
    url = "/posts/"
    weight = 10

[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 20

[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 30

[[menu.main]]
    name = "CV"
    url = "https://tomas-rodriguez-gamboa.github.io/pagina-web/CV_web.pdf"
    weight = 40

[[menu.main]]
    name = "Beyond Economics"
    url = "/beyond-economics/"
    weight = 50